### ISSUE TITLE
Bug: "An error occurred. Try refreshing your browser" - (Brave and ChatGPT Plus)

### ISSUE THREAD

**Issue by tinokaartovuori** [lyr1cx/ChatGPT-Alfred#4]
I installed the workflow and script successfully. However when I am calling the script from Alfred it is not working properly in the browser side. Message "seems" to be inputted to ChatGPT nicely but immediately I get the message `An error occurred. Try refreshing your browser`. If I press `Regenerate response` twice the AI start to write random stuff, fully ignoring the message. If I refresh the page it starts working instantly.

Dev tools console:
```
Failed to load resource: the server responded with a status of 400 ()
_app-a9bac4bbe8d208d2.js:7 Objectdetail: "An error ocurred. Try refreshing your browser."[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(anonymous) @ _app-a9bac4bbe8d208d2.js:7
_app-a9bac4bbe8d208d2.js:7 UserError: An error ocurred. Try refreshing your browser.
    at 814-43da3901d23e78b5.js:1:6528
    at main-149b337e061b4d04.js:1:101106
    at Object.next (main-149b337e061b4d04.js:1:101211)
    at r (_app-a9bac4bbe8d208d2.js:16:1497)
    at a (_app-a9bac4bbe8d208d2.js:16:1694)
```

**Comment by lyr1cx** [comment]
I'm unable to replicate this issue on my end. What was your query to Alfred to get this to trigger?

**Comment by lyr1cx** [comment]
> I installed the workflow and script successfully. However when I am calling the script from Alfred it is not working properly in the browser side. Message "seems" to be inputted to ChatGPT nicely but immediately I get the message `An error occurred. Try refreshing your browser`. If I press `Regenerate response` twice the AI start to write random stuff, fully ignoring the message. If I refresh the page it starts working instantly.
> 
> Dev tools console:
> 
> ```
> Failed to load resource: the server responded with a status of 400 ()
> _app-a9bac4bbe8d208d2.js:7 Objectdetail: "An error ocurred. Try refreshing your browser."[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
> (anonymous) @ _app-a9bac4bbe8d208d2.js:7
> _app-a9bac4bbe8d208d2.js:7 UserError: An error ocurred. Try refreshing your browser.
>     at 814-43da3901d23e78b5.js:1:6528
>     at main-149b337e061b4d04.js:1:101106
>     at Object.next (main-149b337e061b4d04.js:1:101211)
>     at r (_app-a9bac4bbe8d208d2.js:16:1497)
>     at a (_app-a9bac4bbe8d208d2.js:16:1694)
> ```

I'm unable to replicate this issue on my end. What was your query to Alfred to get this to trigger?

**Comment by tinokaartovuori** [comment]
I'm can perform additional testing, such as disabling other extensions, to see if that helps resolve the issue.

When I used the "ai {message}" command in Alfred, the message content didn't seem to affect to the outcome. However, I was able to fix the issue by introducing a 500ms delay before send button is clicked. While this solution worked, I think that it may not be the most elegant or efficient approach to solve this.

I will get back to you when I have done some little testing.

**Comment by tinokaartovuori** [comment]
Now when I am testing this it's working very well. I don't know why it was not working yesterday. I will do further testing in  and check if it works in the near future.

One annoying thing that I noticed is that the "+" sign is not working with this setup.

**Comment by lyr1cx** [comment]
Yeah, I did notice that it does not handle special characters. I need to figure out how to leverage encodeURI or something similar. I'm not the best at JS.

**Comment by lyr1cx** [comment]
The special characters will be fixed in the latest update here soon. It's a simple tick box within the alfred workflow itself I found out via someone submitting a MR and me looking at the changes.
